In [1]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding,Flatten
from tensorflow.keras.datasets import imdb

In [2]:
(X_train,y_train),(X_text,y_test) = imdb.load_data(num_words=10000)

In [3]:
X_train.shape

(25000,)

In [4]:
import numpy as np


In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_text = pad_sequences(X_text,padding='post',maxlen=50)

In [7]:
X_train.shape

(25000, 50)

In [8]:
model = Sequential()

In [9]:

model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.build(input_shape=(None, 50))  # batch_size can be None
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,validation_data=(X_text,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 17ms/step - accuracy: 0.5205 - loss: 0.6921 - val_accuracy: 0.6045 - val_loss: 0.6519
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - accuracy: 0.7305 - loss: 0.5309 - val_accuracy: 0.7974 - val_loss: 0.4390
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 16ms/step - accuracy: 0.8620 - loss: 0.3318 - val_accuracy: 0.7998 - val_loss: 0.4414
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - accuracy: 0.8934 - loss: 0.2654 - val_accuracy: 0.8023 - val_loss: 0.5037
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 16ms/step - accuracy: 0.9136 - loss: 0.2211 - val_accuracy: 0.7984 - val_loss: 0.5031


In [12]:
pred=model.predict(X_text)
print(pred)

782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step
[[0.02364939]
 [0.9702627 ]
 [0.76432186]
 ...
 [0.08659793]
 [0.04923705]
 [0.9059576 ]]


In [14]:
pred[0][0]

np.float32(0.023649389)

In [17]:
embedding_layer = model.layers[0]  # Get the Embedding layer
embedding_weights = embedding_layer.get_weights()[0]  # Shape: (10000, 2)
print(embedding_weights)

[[-0.01234282 -0.0178585 ]
 [-0.09893288 -0.02909508]
 [ 0.00281908 -0.0023547 ]
 ...
 [-0.07629984 -0.0384614 ]
 [ 0.00024326  0.03264343]
 [-0.15335707 -0.1634919 ]]


In [20]:
X_text[0]

array([ 394,  354,    4,  123,    9, 1035, 1035, 1035,   10,   10,   13,
         92,  124,   89,  488, 7944,  100,   28, 1668,   14,   31,   23,
         27, 7479,   29,  220,  468,    8,  124,   14,  286,  170,    8,
        157,   46,    5,   27,  239,   16,  179,    2,   38,   32,   25,
       7944,  451,  202,   14,    6,  717], dtype=int32)

In [22]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb

# Load the IMDB word index
word_index = imdb.get_word_index()

# Reverse the word index to map integer indices to words
index_to_word = {index: word for word, index in word_index.items()}

# Get the embedding layer weights
embedding_layer = model.layers[0]
embedding_weights = embedding_layer.get_weights()[0]  # Shape: (10000, 2)

# Example: Get the word and embedding for the first word in the first test sample
sample_index = 0  # First test sample
word_index_in_sequence = X_text[sample_index][0]  # First word in the sequence

# Map the integer index to the word
word = index_to_word.get(word_index_in_sequence, "<UNKNOWN>")
print(f"Word: {word}")

# Get the embedding vector for the word
embedding_vector = embedding_weights[word_index_in_sequence]
print(f"Embedding vector: {embedding_vector}")

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step
Word: getting
Embedding vector: [0.2522821  0.19118622]


In [23]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb

# 1. Load the IMDB word index (word -> integer mapping)
word_index = imdb.get_word_index()

# 2. Reverse it (integer -> word)
index_to_word = {index: word for word, index in word_index.items()}

# 3. Decode the first sentence in X_text
first_sentence_indices = X_text[0]  # Get the first sentence (list of integers)
first_sentence_words = []

for index in first_sentence_indices:
    # Indices 0, 1, 2 are reserved for padding, start token, and unknown
    if index >= 3:  # Shift index by 3 since IMDB reserves first 3 indices
        word = index_to_word.get(index - 3, "?")  # "?" if word not found
    else:
        word = "?"  # Unknown (padding/placeholder)
    first_sentence_words.append(word)

# Join the words to form the sentence
first_sentence = " ".join(first_sentence_words)
print("First sentence in X_test:")
print(first_sentence)

First sentence in X_test:
terrible performances the show is flat flat flat br br i don't know how michael madison could have allowed this one on his plate he almost seemed to know this wasn't going to work out and his performance was quite ? so all you madison fans give this a miss


In [24]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb

# Load the IMDB word index
word_index = imdb.get_word_index()

# Reverse the word index to map integer indices to words
index_to_word = {index: word for word, index in word_index.items()}

# Get the first sentence (list of integer indices)
first_sentence_indices = X_text[0]

# Get the embedding layer weights (shape: [vocab_size, embedding_dim])
embedding_layer = model.layers[0]
embedding_weights = embedding_layer.get_weights()[0]

# Print each word with its index and embedding vector
print("First sentence with indices and embeddings:")
for position, index in enumerate(first_sentence_indices):
    if index >= 3:  # IMDB reserves 0,1,2 for special tokens
        word = index_to_word.get(index - 3, "?")  # Shift index by 3
        vector = embedding_weights[index]
    else:
        word = "?"  # Placeholder for padding/unknown
        vector = "[PADDING]"

    print(f"Position {position}: Index={index}, Word='{word}', Embedding={vector}")

First sentence with indices and embeddings:
Position 0: Index=394, Word='terrible', Embedding=[0.2522821  0.19118622]
Position 1: Index=354, Word='performances', Embedding=[-0.03896452 -0.10041937]
Position 2: Index=4, Word='the', Embedding=[-0.02859928 -0.01228904]
Position 3: Index=123, Word='show', Embedding=[ 0.02203703 -0.04246587]
Position 4: Index=9, Word='is', Embedding=[-0.01728423 -0.02527518]
Position 5: Index=1035, Word='flat', Embedding=[ 0.11881304 -0.05880819]
Position 6: Index=1035, Word='flat', Embedding=[ 0.11881304 -0.05880819]
Position 7: Index=1035, Word='flat', Embedding=[ 0.11881304 -0.05880819]
Position 8: Index=10, Word='br', Embedding=[ 0.00966143 -0.00535883]
Position 9: Index=10, Word='br', Embedding=[ 0.00966143 -0.00535883]
Position 10: Index=13, Word='i', Embedding=[-0.03384641 -0.00185681]
Position 11: Index=92, Word='don't', Embedding=[-0.00356671  0.04518733]
Position 12: Index=124, Word='know', Embedding=[-0.03642732 -0.0562656 ]
Position 13: Index=89

In [25]:
X_text[0]

array([ 394,  354,    4,  123,    9, 1035, 1035, 1035,   10,   10,   13,
         92,  124,   89,  488, 7944,  100,   28, 1668,   14,   31,   23,
         27, 7479,   29,  220,  468,    8,  124,   14,  286,  170,    8,
        157,   46,    5,   27,  239,   16,  179,    2,   38,   32,   25,
       7944,  451,  202,   14,    6,  717], dtype=int32)